/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 protein63Draco.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/proteins/protein63.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.79, 36.54, 0.76]} rotation={[-0.09, -0.48, -0.21]}>
        <mesh geometry={nodes.subnode_0.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_1.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_10.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_11.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_12.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_13.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_14.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_15.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_16.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_17.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_18.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_19.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_2.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_20.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_21.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_22.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_23.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_24.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_25.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_26.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_27.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_3.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_4.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_5.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_6.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_7.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_8.geometry} material={materials.material_0} />
        <mesh geometry={nodes.subnode_9.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/proteins/protein63.glb')
