/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 slipknotDraco.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/proteins/slipknot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.subnode_0.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_1.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_10.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_11.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_12.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_13.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_14.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_2.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_3.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_4.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_5.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_6.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_7.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_8.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
      <mesh geometry={nodes.subnode_9.geometry} material={materials.material_0} position={[87.83, 15.88, 1.11]} rotation={[-1.58, -0.54, 2.33]} scale={1.20} />
    </group>
  )
}

useGLTF.preload('/proteins/slipknot.glb')
