/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 knotDraco.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/knotDraco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.16, -0.67, -1.99]} rotation={[-0.06, -0.07, 0.35]} scale={[1.1, 1.1, 1.1]}>
        <mesh geometry={nodes.subnode_0.geometry} material={materials.material_0} position={[0.74, -1.47, 17.63]} />
        <mesh geometry={nodes.subnode_1.geometry} material={materials.material_0} position={[0.74, -1.47, 17.63]} />
        <mesh geometry={nodes.subnode_2.geometry} material={materials.material_0} position={[0.74, -1.47, 17.63]} />
        <mesh geometry={nodes.subnode_3.geometry} material={materials.material_0} position={[0.74, -1.47, 17.63]} />
        <mesh geometry={nodes.subnode_4.geometry} material={materials.material_0} position={[0.74, -1.47, 17.63]} />
      </group>
    </group>
  )
}

useGLTF.preload('/knotDraco-transformed.glb')
