import Head from 'next/head';
import Navbar from '@/components/Nav';
import Search from '@/components/Search';
import About from '@/components/About';
import MyStructure from '@/components/MyStructure';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Alphaknot 3D</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="img/logo.png" />
      </Head>
      <Navbar/>
      <Search/>
      <About/>
      <MyStructure/>
      <Footer/>
    </>
  )
}
